In [4]:
import numpy as np
# 3.1 1D NumPy Arrays
list = [20, 27, 9, 12, 31, 17, 4, 50, 39, 35] 
arr = np.array(list)
print(arr) 

[20 27  9 12 31 17  4 50 39 35]


In [5]:
print(arr * 4)

[ 80 108  36  48 124  68  16 200 156 140]


In [6]:
print(np.mean(arr))

24.4


In [7]:
print(np.median(arr)) 
print(np.std(arr)) 

23.5
13.828955130450023


In [8]:
print(arr[np.argmin(arr)], arr[np.argmax(arr)]) 

4 50


In [9]:
print(np.min(arr), np.max(arr)) #matches the values from previous step

4 50


In [10]:
arr_20 = arr[arr > 20]
print(arr_20)

[27 31 50 39 35]


In [11]:
# 3.2 2D NumPy Arrays
list = [
[5, 12, 17, 9],
[8, 21, 14, 3],
[6, 13, 19, 11]
]
matrix = np.array(list)
print(np.shape(matrix)) # --> 3 rows and 4 columns

(3, 4)


In [12]:
print(matrix[:, 2]) 

[17 14 19]


In [13]:
print(matrix[2, :])

[ 6 13 19 11]


In [14]:
print(matrix * 2) 

[[10 24 34 18]
 [16 42 28  6]
 [12 26 38 22]]


In [15]:
for x in range(0,3)  : 
    print(np.mean(matrix[:, x])) 

6.333333333333333
15.333333333333334
16.666666666666668


In [16]:
print(np.mean(matrix))

11.5


In [17]:
for x in range(0, 3) : 
    print(f" row {x} has max value {np.max(matrix[x, :])}")
for x in range(0,4) : 
    print(f" col {x} has min value {np.min(matrix[:, x])}")

 row 0 has max value 17
 row 1 has max value 21
 row 2 has max value 19
 col 0 has min value 5
 col 1 has min value 12
 col 2 has min value 14
 col 3 has min value 3


In [18]:
matrix_2 = matrix.flatten()
print(matrix_2) # new shape is a single row matrix with all of the entries

[ 5 12 17  9  8 21 14  3  6 13 19 11]


In [19]:
print(np.argmin(matrix.flatten()), np.argmax(matrix.flatten()))

7 5


In [20]:
flat_indices = np.arange(matrix.size)
rows, cols = np.unravel_index(flat_indices , matrix.shape)
print(rows, cols)

[0 0 0 0 1 1 1 1 2 2 2 2] [0 1 2 3 0 1 2 3 0 1 2 3]


In [21]:
matrix_15 = matrix[matrix > 15]
print(matrix_15) 

[17 21 19]


In [22]:
print(np.sort(matrix))

[[ 5  9 12 17]
 [ 3  8 14 21]
 [ 6 11 13 19]]


In [23]:
#  Prime Star Systems
arr_mag = np.array([
[2, 3, 5],
[14, 6, 8],
[11, 13, 17],
[7, 10, 13]
])

def sort_prime(array) :
    prime_arr = ([])
    prime = False
    
    for row in array :
        
        for x in row :
            prime = True
            
            if x <= 1 : 
                prime = False
                
            for i in range(2, x) : 
                if x % i == 0 :
                    prime = False
                    break 
                    
        for x in row :
            
            if prime == True : 
                prime_arr.append(row)     
                break
            
    return np.array(prime_arr)

print(sort_prime(arr_mag)) 

[[ 2  3  5]
 [11 13 17]
 [ 7 10 13]]


In [24]:
# 5 Checkers
# 5.1 
def create_checkerboard(y) : 
    board = [[0 for _ in range(y)] for _ in range(y)] 
    for row in board : 
        print(row) 
        
game_board = create_checkerboard(8)

[0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0]


In [25]:
# 5.2
def board_fill(num):
    array = []
    for row_idx in range(num):
        start = 1 if row_idx % 2 == 0 else 0 # if we want it to start with a 1 we just change row_idx % 2 == 0 instead of 1 
        row = [(start + col_idx) % 2 for col_idx in range(num)]
        array.append(row)
    return array

print(board_fill(8))
        
def reverse_board_fill(num):
    array = []
    for row_idx in range(num):
        start = 0 if row_idx % 2 == 0 else 1
        row = [(start + col_idx) % 2 for col_idx in range(num)]
        array.append(row)
    return array 

print(reverse_board_fill(8))

[[1, 0, 1, 0, 1, 0, 1, 0], [0, 1, 0, 1, 0, 1, 0, 1], [1, 0, 1, 0, 1, 0, 1, 0], [0, 1, 0, 1, 0, 1, 0, 1], [1, 0, 1, 0, 1, 0, 1, 0], [0, 1, 0, 1, 0, 1, 0, 1], [1, 0, 1, 0, 1, 0, 1, 0], [0, 1, 0, 1, 0, 1, 0, 1]]
[[0, 1, 0, 1, 0, 1, 0, 1], [1, 0, 1, 0, 1, 0, 1, 0], [0, 1, 0, 1, 0, 1, 0, 1], [1, 0, 1, 0, 1, 0, 1, 0], [0, 1, 0, 1, 0, 1, 0, 1], [1, 0, 1, 0, 1, 0, 1, 0], [0, 1, 0, 1, 0, 1, 0, 1], [1, 0, 1, 0, 1, 0, 1, 0]]


In [37]:
# 6 Expanding Universe
def expand(array, num) : 
    x = 0
    expanded_array = []
    for word in array: 
        expanded_word = []
        n = len(word) 
        
        for i in range(n) : 
            expanded_word.append(word[i])
            
            if i != n-1 : 
                expanded_word.append(" " * num)
                
        expanded_array.append("".join(expanded_word))
    return expanded_array 

universe = np.array(['Galaxy', 'clusters'])
print(expand(universe, 2))
            

['G  a  l  a  x  y', 'c  l  u  s  t  e  r  s']


In [45]:
# 7. Second-Brightest Star
def second_brightest(array) : 

    second_brightest_values = []
    
    for row in array : 
        
        brightest_value = 0
        second_brightest_value = 0 
        
        for num in row : 
            
            if num > brightest_value : 
                second_brightest_value = brightest_value
                brightest_value = num 
                
            elif num > second_brightest_value :
                second_brightest_value = num
                
        second_brightest_values.append(int(second_brightest_value))
        
    return f"The second brightest values are {second_brightest_values}."

stars = np.array([[1123, 1456, 1789, 1324, 1876],
[1567, 1987, 1678, 1405, 1589],
[1345, 1654, 1523, 1109, 1923],
[1298, 1890, 1367, 1784, 1432],
[1823, 1756, 1489, 1672, 1550]])

print(second_brightest(stars)) 

The second brightest values are [1789, 1678, 1654, 1784, 1756].
